accounts/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("signup/", views.SignUp.as_view(), name="signup"),
]

orders/urls.py
from django.urls import path

from .views import (
    MenuView,
    add_to_cart,
    cart,
    decrease_quantity,
    increase_quantity,
    index,
    product_detail,
    remove_from_cart,
)

app_name = "orders"

urlpatterns = [
    path("", index, name="home"),
    path("menu", MenuView.as_view(), name="menu"),
    path("add-to-cart/", add_to_cart, name="add-to-cart"),
    path("remove-from-cart/<order_item_id>", remove_from_cart, name="remove-from-cart"),
    path("cart", cart, name="cart"),
    path("details/<str:slug>", product_detail, name="product_detial"),
    path("decrease/<order_item_id>", decrease_quantity, name="decrease-quantity"),
    path("increase/<order_item_id>", increase_quantity, name="increase-quantity"),
]

urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("orders.urls", namespace="orders")),
    path("accounts/", include("accounts.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
]

accounts/models.py
from django.db import models

# Create your models here.

orders/models.py
import decimal

from django.conf import settings
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=32)
    only_one_price = models.BooleanField(default=False)

    def __str__(self):
        return self.name


class Topping(models.Model):
    name = models.CharField(max_length=32)
    price = models.DecimalField(max_digits=5, decimal_places=2)

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=32)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    slug = models.SlugField()
    small_price = models.DecimalField(max_digits=5, decimal_places=2)
    large_price = models.DecimalField(
        null=True, blank=True, max_digits=5, decimal_places=2
    )

    def __str__(self):
        return self.name


class Cart(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField(null=True)
    ordered = models.BooleanField(default=False)
    value = models.DecimalField(max_digits=5, decimal_places=2, default=0)

    def __str__(self):
        return f"{self.user.username} cart"


class OrderItem(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, null=True, blank=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveSmallIntegerField(default=1)
    size = models.CharField(
        max_length=16, choices=(("S", "Small"), ("L", "Large")), default="S"
    )
    toppings = models.ManyToManyField(Topping, blank=True)

    @property
    def value(self):
        return self.get_single_product_value() * self.quantity

    def get_single_product_value(self):
        if self.size == "S":
            value = self.product.small_price
        else:
            value = self.product.large_price
        if self.toppings:
            for topping in self.toppings.all():
                value = decimal.Decimal(value) + topping.price
        return value

    def __str__(self):
        return f"{self.quantity} {self.size} {self.product}"

orders/forms.py
from django import forms

from .models import OrderItem


class ProductDetailsForm(forms.ModelForm):
    class Meta:
        model = OrderItem
        fields = ["size", "quantity", "toppings"]

accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic


class SignUp(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy("login")
    template_name = "registration/signup.html"

orders/views.py
from django.contrib import messages
from django.db.models import Count
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.utils import timezone
from django.views.generic import ListView

from .forms import ProductDetailsForm
from .models import *


def index(request):
    return render(request, "orders/index.html")


# Class view
class MenuView(ListView):
    model = Product
    template_name = "orders/menu.html"


def cart(request):
    context = {"cart": Cart.objects.get(user=request.user, ordered=False)}
    return render(request, "orders/cart.html", context)


def product_detail(request, slug):
    form = ProductDetailsForm(request.POST or None)
    product = Product.objects.get(slug=slug)
    product_information = {"user": request.user, "product": product}
    if form.is_valid():
        product_information.update(form.cleaned_data)
        return add_to_cart(request, data=product_information)
    context = {"form": form, "product": product}
    return render(request, "orders/productDetails.html", context)


def add_to_cart(request, data):
    user = data.pop("user")
    cart, created = Cart.objects.get_or_create(user=user, ordered=False)
    order_item = get_or_create_order_item(data)
    cart.value += order_item.value
    cart.save()

    if created or order_item not in cart.orderitem_set.all():
        order_item.cart = cart
        order_item.save()
    return redirect("orders:menu")


def get_or_create_order_item(data):
    toppings = data.pop("toppings")
    order_item = (
        OrderItem.objects.filter(
            product=data["product"], size=data["size"], toppings__in=toppings,
        )
        .annotate(num_topping=Count("toppings"))
        .filter(num_topping=len(toppings))
        .first()
    )
    if order_item:
        order_item.quantity += data["quantity"]
        order_item.save()

    if not order_item:
        order_item = OrderItem(
            product=data["product"], size=data["size"], quantity=data["quantity"],
        )
        order_item.save()
        for topping in toppings:
            order_item.toppings.add(topping)
            order_item.save()
    return order_item


def remove_from_cart(request, order_item_id):
    order_item = OrderItem.objects.get(id=order_item_id)
    cart = order_item.cart
    cart.value -= order_item.value
    order_item.delete()
    cart.save()
    return redirect("orders:cart")


def decrease_quantity(request, order_item_id):
    order_item = OrderItem.objects.get(id=order_item_id)
    cart = order_item.cart
    cart.value -= order_item.get_single_product_value()
    if order_item.quantity > 1:
        order_item.quantity -= 1
    else:
        order_item.delete()
    order_item.save()
    cart.save()
    return redirect("orders:cart")


def increase_quantity(request, order_item_id):
    order_item = OrderItem.objects.get(id=order_item_id)
    cart = order_item.cart
    order_item.quantity += 1
    cart.value += order_item.get_single_product_value()
    order_item.save()
    cart.save()
    return redirect("orders:cart")

templates/base.html
{% load static %}
<html lang="en">
  <head>
   <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
{##}
{#    <!-- Bootstrap CSS -->#}
{#    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">#}
{#    #}

      <link href="{% static "orders/styles.css" %}" rel="stylesheet" type="text/css"/>

    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>

  <header>
      <div class="container">

          <img src="{% static "orders/images/pinokionavbar.jpg" %}" alt="logo" class="logo"/>

          <nav>
            <a href="/">Home</a>
            <a href="/menu">Menu</a>
            <a href="#">Contact</a>
          <div class="logging-in">
            {% if user.is_authenticated %}
                <a href="{% url 'orders:cart' %}"> {{ user.username }}</a>
                <a href="{% url 'logout' %}">logout</a>
            {% else %}
                <a href="{% url 'login' %}">Login</a>
                <a href="{% url 'signup' %}">Sign up</a>
            {% endif %}
          </div>
          </nav>

      </div>
  </header>
         {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
          {% endif %}
      {% block body %}{% endblock %}
  </body>
</html>

templates/orders/cart.html
{% extends "base.html" %}
{% block title %}
    Pizzernia
{% endblock %}
{% block body %}
    <h1>{{ cart }} </h1> 
    {% for product in cart.orderitem_set.all %}
        {{ product.product }} {{ product.quantity}} 
        <a href="{% url 'orders:remove-from-cart' product.id %}">Remove</a> 
        <a href="{% url 'orders:decrease-quantity' product.id %}">decrease</a>
        <a href="{% url 'orders:increase-quantity' product.id %}">increase</a>
        <br>  
    {% endfor %}
    <p> suma zamowienia {{ cart.value}}</p>
{% endblock %}

templates/orders/index.html
{% extends "base.html" %}
{% block title %}
    Pizzernia
{% endblock %}
{% block body %}
    <h1>Siemanko witam w mojej pizzerni</h1>
{% endblock %}

templates/orders/menu.html
{% extends "base.html" %}
{% block title %}
    Pizzernia-menu
{% endblock %}
{% block body %}
    {% load static %}
    <h1>Menu</h1>
    <table>
        <tr>
            <th>Name</th>
            <th>Small</th>
            <th>Large</th>
        </tr>
        {% for product in object_list %}
            
                <tr>
                    <th>{{ product }}</th>
                    <th>{{ product.small_price }}</th>
                    {% if product.large_price %}
                        <th>{{ product.large_price }}</th>
                    {% endif %}
                    <th><a href="{% url 'orders:product_detial' product.slug %}">Order</a></th>
                </tr>
        {% endfor %}
    </table>

{% endblock %}

templates/orders/productDetails.html
<!doctype html>

<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Product details</title>
</head>

<body>
    <form method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Add to cart">
    </form>
</body>
</html>